; caps
#HotIf capslock_pressed
#Include .\caps\1.ahk
#Include .\caps\2.ahk
#Include .\caps\3.ahk
#Include .\caps\4.ahk
#Include .\caps\5.ahk
#Include .\caps\mouse.ahk
#HotIf
; bar
#Include .\bar\1.ahk
#Include .\bar\2.ahk
#Include .\bar\3.ahk
#Include .\bar\4.ahk
#Include .\bar\5.ahk
#Include .\bar\mouse.ahk
; shift
#Include .\shift\4.ahk
#Include .\shift\5.ahk

; x1
#Include .\x1\mouse.ahk
; x2
#Include .\x2\mouse.ahk
#Include .\x2\1.ahk
#Include .\x2\2.ahk
#Include .\x2\3.ahk
#Include .\x2\4.ahk
#Include .\x2\5.ahk