import { header, sidebar, base } from "./length.jsx";
import tone from "../style/color.jsx";
import zObj from "../obj/zObj.js";

const look = {
  download2: {
    position: "absolute",
    left: "10px",
    backgroundColor: tone.OftenGridColor,
  },
  download1: {
    position: "absolute",
    right: "10px",
    backgroundColor: tone.AccentColor,
  },
  alertLabel1: {
    position: "relative",
    alignItems: "center",
    whiteSpace: "nowrap",
    zIndex: 1,
    display: "flex",
    paddingLeft: `calc(${base} * 0)`,
    fontSize: `calc(${base} * 14)`,
    pointerEvents: "none",
  },
  unusable1: { fontSize: `calc(${base} * 10)` },
  ToggleBaseStyle: (value) => ({
    width: `calc(${base} * 40)`,
    height: `calc(${base} * 20)`,
    borderRadius: `calc(${base} * 20)`,
    backgroundColor: value ? tone.violetTextColor : "#3A3A3C",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  }),
  ToggleKnobStyle: (value) => ({
    width: `calc(${base} * 18)`,
    height: `calc(${base} * 18)`,
    borderRadius: "50%",
    backgroundColor: "#E5E5E5",
    position: "absolute",
    top: `calc(${base} * 1)`,
    left: value ? `calc(${base} * 21)` : `calc(${base} * 1)`,
    boxShadow: `0 calc(${base} * 2) calc(${base} * 2) rgba(0, 0, 0, 0.4)`,
    transition: "left 0.2s ease",
  }),
  Arrow1: {
    position: "absolute",
    right: 0,
    top: "-4px",
    width: 0,
    height: 0,
    borderTop: "5px solid transparent",
    borderBottom: "5px solid transparent",
    borderLeft: "8px solid white",
  },
  sidebar1: {
    display: "flex",
    // alignItems: "center",
    width: "100%",
    // justifyContent: "center",
    // backgroundColor: "#888888",
    // fontSize: `calc(${base} * 20)`,
    // color: tone.TextColor,
    gap: 10,
    paddingTop: 10,
    paddingBottom: 10,
    // backgroundColor: "red",
  },
  script1: {
    height: 200,
    position: "relative",
    // margin: 10,
    backgroundColor: "#444",
    overflowY: "scroll",
    whiteSpace: "pre-wrap",
    // // flex: 1,
    // backgroundColor: "red",
  },
  copy1: {
    marginTop: 10,
    position: "sticky",
    top: 0,
    backgroundColor: "#333333",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    width: "100%",
    height: "56px",
    fontSize: "16px",
    paddingTop: 10,
    // paddingBottom: 10,
  },
  reset1: {
    position: "sticky",
    top: 0,
    backgroundColor: "#e74c3c",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    width: "100%",
    height: "56px",
    fontSize: "16px",
  },
  sidebar2: {
    position: "relative",
    padding: 10,
  },
  Multi3: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100%",
    justifyContent: "center",
    // backgroundColor: "#888888",
    fontSize: `calc(${base} * 20)`,
    color: tone.TextColor,
    gap: `calc(${base} * 5)`,
  },
  Multi2: (col) => ({
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    justifyContent: "center",
    backgroundColor: col.buttonColor,
    fontSize: `calc(${base} * 20)`,
  }),
  Multi1: {
    position: "relative",
    // backgroundColor: BorderColor,
  },
  tgButton6: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)", // ★ 完全中央
    fontSize: `calc(${base} * 15)`,
    color: tone.circleColor,
    zIndex: 2, // ★ ラベルの上に重ねる
    pointerEvents: "none",
    backgroundColor: "blue",
  },
  tgButton5: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)", // ★ 完全中央

    fontSize: `calc(${base} * 20)`,
    color: tone.circleColor,
    zIndex: 2, // ★ ラベルの上に重ねる
    pointerEvents: "none",
    backgroundColor: "yellow",
  },
  tgButton4: {
    position: "absolute",
    right: "0",
    top: "0",
    aspectRatio: "1 / 1",
    height: "100%",
    // width: `calc(${base} * 34)`,
    // top: `calc(${base} * -4)`,

    // fontSize: `calc(${base} * 32)`,
    // color: tone.TextColor,
    // zIndex: 2, // ★ ラベルの上に重ねる
    // pointerEvents: "none",
    // backgroundColor: "yellow",
  },
  tgButton9: {
    position: "absolute",
    right: `calc(${base} * 2)`,
    top: `calc(${base} * 2)`,
    aspectRatio: "1 / 1",
    height: `calc(${base} * 18)`,
    width: `calc(${base} * 18)`,
    zIndex: 21,
    backgroundColor: "pink",
  },
  tgButton10: {
    position: "absolute",
    right: `calc(${base} * 20)`,
    top: `calc(${base} * 2)`,
    aspectRatio: "1 / 1",
    height: `calc(${base} * 18)`,
    width: `calc(${base} * 18)`,
    backgroundColor: "yellow",
  },
  tgButton7: {
    position: "absolute",
    right: `calc(${base} * -3)`, // ★ 右から base*8
    top: `calc(${base} * -7)`, // ★ 右から base*8
    // aspectRatio: "1 / 1",
    height: "100%",
    fontSize: `calc(${base} * 24)`,
    // backgroundColor: "yellow",
    zIndex: 4,
  },

  tgButton11: {
    position: "absolute",
    left: `calc(${base} * -3)`, // ★ 右から base*8
    top: `calc(${base} * -7)`, // ★ 右から base*8
    // aspectRatio: "1 / 1",
    height: "100%",
    fontSize: `calc(${base} * 24)`,
    backgroundColor: "yellow",
    zIndex: 4,
  },

  tgButton3: (col) => ({
    position: "relative", // ← 重ねの基準
    // display: "inline-flex",
    alignItems: "center",
    whiteSpace: "nowrap",
    // position: "relative",
    zIndex: 1,
    display: "flex",
    // alignItems: "center",
    paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 14)`,
    color: col.textColor,
    pointerEvents: "none",
  }),

  tgButton12: {
    position: "absolute",
    backgroundColor: tone.homePositionColor,
    height: "10%",
    width: "15%",
    top: "75%",
    left: "50%",
    transform: "translateX(-50%)",
    borderRadius: `calc(${base} * 20)`,
  },
  tgButton8: {
    position: "absolute",
    top: 0,
    right: 0,
    // backgroundColor: "red",
    height: "100%",
    aspectRatio: "1 / 1", // 高さに合わせて幅も同じに
  },

  tgButton2: (col) => ({
    // position: "absolute",
    position: "relative", // ★ 重ね基準
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    backgroundColor: col.buttonColor,
  }),

  tgButton1: (styleObj, roo, col, boo) => ({
    position: "absolute",
    width: "100%",
    height: "100%",
    cursor: roo.isCursorPointer ? "pointer" : "default",
    backgroundColor: col.borderColor,
    ...styleObj,
    zIndex: boo?.isHd ? zObj.hdTgEle : zObj.notHdTgEle,
  }),
  tg_Index1: {
    flex: 1,
    display: "flex",
  },
  ac_Matrix_Button2: {
    display: "flex",
    justifyContent: "center", // 横中央
    alignItems: "center", // 縦中央
    color: tone.TextColor, // ← やさしい白
  },
  BasicButtons3: {
    display: "flex",
    alignItems: "center",
    // paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 18)`,
    color: "#22C55E",
    marginRight: `calc(${base} * 4)`, // ← 右からの距離
    marginLeft: "auto",
  },
  BasicButtons2: {
    display: "flex",
    alignItems: "center",
    // paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 18)`,
    color: "yellow",
    marginRight: `calc(${base} * 4)`, // ← 右からの距離
    marginLeft: "auto",
  },
  acButton5: {
    position: "absolute",
    right: `calc(${base} * -1)`,
    top: `calc(${base} * 1)`,

    display: "flex",
    alignItems: "center",
    fontSize: `calc(${base} * 13)`,
    color: "#22C55E",
  },
  acButton4: {
    position: "absolute",
    right: `calc(${base} * 2)`,
    top: `calc(${base} * 1)`,

    display: "flex",
    alignItems: "center",
    fontSize: `calc(${base} * 13 )`,
    color: "yellow",
  },
  multi1: {
    // display: "flex",
    // alignItems: "center",
    // justifyContent: "center",
    // paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    // gap: `calc(${base} * 2)`,
  },
  multi2: {
    // display: "flex",
    // alignItems: "center",
    // justifyContent: "center",
    // paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 15)`,
    // color: tone.TextColor,
    // gap: `calc(${base} * 2)`,
  },
  BasicButtons1: (col) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: `calc(${base} * 8)`,
    fontSize: `calc(${base} * 15)`,
    color: col.textColor,
  }),
  acButton3: (boo) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: `calc(${base} * 3)`,
    fontSize: `calc(${base} * 15)`,
    color: tone.TextColor,
    textDecorationLine: boo.isImportant ? "underline" : "none",
    textDecorationThickness: `calc(${base} * 7)`,
    textUnderlineOffset: `calc(${base} * 2)`,
    textDecorationSkipInk: "none",
    // gap: `calc(${base} * 2)`,
  }),
  acButton2: (col) => ({
    position: "absolute",
    top: "50%",
    left: "50%",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    transform: "translate(-50%, -50%)",
    backgroundColor: col.buttonColor,
  }),
  acButton1: (styleObj, col) => ({
    position: "absolute",
    width: "100%",
    height: "100%",
    zIndex: 2,
    backgroundColor: col.borderColor,
    ...styleObj,
  }),
  ac_Matrix1: {
    position: "absolute",
  },
  TgCap5: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  TgCap4: {
    pointerEvents: "none",
    backgroundColor: tone.RemoteHoveredColor,
    color: tone.TextColor,
  },
  TgCap2: (col) => ({
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingLeft: `calc(${base} * 8)`,
    minHeight: 0,
    fontSize: `calc(${base} * 18)`,
    gap: `calc(${base} * 2)`,
    color: col.textColor,
  }),
  ac_Index_Button2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 0,
    fontSize: `calc(${base} * 22)`,
  },
  Body1: {
    position: "absolute",
    top: header,
    left: sidebar,
    right: 0,
    bottom: 0,
    flexDirection: "column",
    overflowX: "hidden", // ★ 横スクロール完全遮断
    overflowY: "auto",
    display: "flex",

    backgroundColor: "#888",
  },
  Body2: {
    flexShrink: 0, // ★ これが本命
    maxHeight: "100%",
    aspectRatio: "16 / 9",
    // flexShrink: 0, // ★ 高さを勝手に潰されない
    display: "flex",
    flexDirection: "column",

    overflow: "hidden",
    backgroundColor: "#608000",
  },
  Body8: {
    flex: 1,
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  Body7: {
    flex: 1,
    width: "100%",
    height: "100%",
    display: "flex",
    // flexDirection: "column",
  },
  Body3: {
    flex: 5,
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  Body4: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  Body5: {
    position: "relative",
    top: "50%",
    left: "50%",
    width: "90%",
    height: "90%",
    transform: "translate(-50%, -50%)",
    backgroundColor: tone.NormalIndexBorderColor,
    display: "flex",
    flexDirection: "column",
  },
  Body6: {
    flexShrink: 0, // 自然な高さを保つ
    minHeight: "300px", // ← 試しに
    position: "relative",
    display: "BlockColor",
    margin: "0 auto",
    whiteSpace: "pre-wrap",
    backgroundColor: "#1e1e1e",
    color: "#6cf",
    // padding: "0px",
    // marginTop: "0px",
    // borderRadius: "0px",
    fontFamily: "monospace",
    userSelect: "TextColor",
  },
  ac1: {
    flex: 1,
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
  },
  ac5: {
    flex: 11,
    display: "flex",
    position: "relative",
    backgroundColor: tone.buttonsBgColor,
    flexDirection: "column",
  },
  ac4: {
    flex: 2,
    display: "flex",
    flexDirection: "row",
    backgroundColor: "yellow",
    alignItems: "center",
    justifyContent: "center",
  },
  ac2: {
    flex: 2,
    display: "flex",
    flexDirection: "row",
    backgroundColor: tone.buttonsBgColor,
  },
  ac3: {
    flex: 11,
    display: "flex",
    position: "relative",
    backgroundColor: tone.buttonsBgColor,
  },
  leftPanel: (SgIdMo_ac_display) => ({
    display: SgIdMo_ac_display === "none" ? "flex" : "none",
    position: "relative",
    flex: 1,
    backgroundColor: tone.NormalIndexBorderColor,
    flexDirection: "column",
  }),
  centerPanel: {
    display: "flex",
    position: "relative",
    flex: 8,
    backgroundColor: tone.NormalIndexBorderColor,
    justifyContent: "center",
    alignItems: "center",
  },
  tgBlock5: {
    position: "absolute",
    top: `${100 * (2 / 6)}%`,
    backgroundColor: tone.BlockColor,
    height: `${100 * (2 / 6)}%`,
    left: `${100 * (1.7 / 15)}%`,
    width: `${100 * (11.8 / 15)}%`,
  },
  tgBlock4: {
    position: "absolute",
    top: `${100 * (1 / 6)}%`,
    backgroundColor: tone.BlockColor,
    height: `${100 * (4 / 6)}%`,
    left: `${100 * (2.2 / 15)}%`,
    width: `${100 * (11 / 15)}%`,
  },
  tgBlock3: {
    position: "absolute",
    top: `${100 * (3 / 6)}%`,
    backgroundColor: tone.BlockColor,
    height: `${100 * (1 / 6)}%`,
    left: `${100 * (1.7 / 15)}%`,
    width: `${100 * (12 / 15)}%`,
  },
  tgBlock2: {
    position: "absolute",
    top: `${100 * (1 / 6)}%`,
    backgroundColor: tone.BlockColor,
    height: `${100 * (2 / 6)}%`,
    left: `${100 * (1.5 / 15)}%`,
    width: `${100 * (12 / 15)}%`,
  },
  tgBlock1: {
    position: "absolute",
    top: `${100 * (1 / 6)}%`,
    backgroundColor: tone.BlockColor,
    height: `${100 * (1 / 6)}%`,
    left: `${100 * (1 / 15)}%`,
    width: `${100 * (13 / 15)}%`,
  },
  tg6: {
    position: "fixed",
    zIndex: 999999,
  },
  tg4: {
    position: "relative",
    flex: 2,
    display: "flex",
    flexDirection: "row",
    zIndex: 1,
  },
  tg5: {
    display: "flex",
    alignItems: "center",
    gap: `calc(${base} * 14)`,
    // backgroundColor: "red",
    paddingLeft: `calc(${base} * 8)`,
    paddingRight: `calc(${base} * 8)`,
    border: `calc(${base} * 2) solid ${tone.textWhiteColor}`,
  },
  tg3: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    // backgroundColor: "red",
    height: "100%",
    width: "100%",
    // whiteSpace: "pre-line",
    // display: "flex",
    flexDirection: "column", // ← 縦に並べる
    // alignItems: "center",
    // justifyContent: "center",
    gap: `calc(${base} * 18)`,
  },
  tg2: {
    flex: 11,
    display: "flex",
    position: "relative",
    backgroundColor: tone.buttonsBgColor,
    width: "100%",
    height: "100%",
  },
  tg1: {
    width: "100%",
    height: "100%",
  },
  Sidebar1: {
    position: "fixed",
    top: header,
    left: 0,
    width: sidebar,
    height: `calc(100vh - ${header})`,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#222",
  },
  Header1: {
    position: "fixed",
    top: 0,
    left: 0,
    height: header,
    width: "100%",
    backgroundColor: "#333",
    display: "flex",
    alignItems: "center",
    // padding: "0 16px",
    zIndex: 5,
  },
  Header2: {
    fontSize: "1.5em",
    fontSleepmily: "'Inter Tight', sans-serif",
    fontWeight: 400,
  },
  ac_Index1: {},
  TgCap3: (col) => ({
    position: "absolute",
    top: "50%",
    left: "50%",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    transform: "translate(-50%, -50%)",
    backgroundColor: col.buttonColor,
  }),
  TgCap1: {
    position: "relative",
    flex: 1,
    fontSize: `calc(${base} * 20)`,
    // backC.groundColor: TgCapColor,
    // border: "none",
    cursor: "pointer",
    // overflow: "visible",
    // outline: "none",
    userSelect: "none",
    // backgroundColor: transparent,
  },
  acIndex2: {
    position: "relative",
    flex: 1,
    fontSize: `calc(${base} * 9)`,
    // backC.groundColor: TgCapColor,
    // border: "none",
    cursor: "pointer",
    // overflow: "visible",
    // outline: "none",
    userSelect: "none",
  },
  acIndex1: (col) => ({
    position: "absolute",
    top: "50%",
    left: "50%",
    width: `calc(100% - ${base} * 4)`,
    height: `calc(100% - ${base} * 5)`,
    transform: "translate(-50%, -50%)",
    backgroundColor: col.buttonColor,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  OftenButton3: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100%",
    justifyContent: "flex-start",
    paddingLeft: `calc(${base} * 8)`,
    // backgroundColor: "#888888",
    fontSize: `calc(${base} * 20)`,
    color: tone.TextColor,
    gap: `calc(${base} * 5)`,
  },
  OftenButton2: (ButtonColor) => ({
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    justifyContent: "center",
    fontSize: `calc(${base} * 20)`,
    backgroundColor: ButtonColor,
  }),
  OftenButton1: (BorderColor) => ({
    position: "relative",
    backgroundColor: BorderColor,
    // height: `calc(100% - ${base} * 8)`,
  }),
  OftenBlock2: {
    flex: 1,
    // display: "grid",
    // gridTemplateColumns: `repeat(${Column}, minmax(0, 1fr))`,
    // backgroundColor: isPickedBlock ? tone.AssignedColor : "gray",
    height: `calc(100% - ${base} * 8)`,
    // width: `calc(100% - ${base} * 10)`,
  },
  OftenBlock3: {
    width: `calc(${base} * 100)`,
    // display: "flex",
    // alignItems: "center", // 縦中央
    // paddingLeft: `calc(${base} * 3)`,
    // // justifyContent: "center", // 横中央（不要なら消す）
    // fontWeight: "bold",
    // fontSize: `calc(${base} * 20)`,
    // backgroundColor: tone.OftenIndexColor,
    backgroundColor: "green",
    height: `calc(100% - ${base} * 8)`,
  },
  OftenBlock1: {
    flex: 1,
    display: "flex",
    alignItems: "center", // 縦中央
    paddingLeft: `calc(${base} * 3)`,
    // justifyContent: "center", // 横中央（不要なら消す）
    fontWeight: "bold",
    minWidth: 0,
    fontSize: `calc(${base} * 20)`,
    // backgroundColor: tone.OftenIndexColor,
    backgroundColor: "gray",
    // flexDirection: "row",
  },
  basic8: {
    // display: "flex",
    flex: 1,
    width: "100%",
    position: "relative",
  },
  basic7: {
    display: "flex",
    width: "100%",
    height: "100%",
  },
  basic6: (col) => ({
    alignItems: "center", // ← 縦中央
    display: "flex",
    // alignItems: "center",
    // justifyContent: "center",
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    height: `calc(100% - ${base} * 8)`,
    width: `calc(100% - ${base} * 10)`,
    backgroundColor: col.buttonColor, // デバッグ用（あとで消す）
  }),
  basic5: (col) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    // height: `calc(100% - ${base} * 8)`,
    // width: `calc(100% - ${base} * 10)`,
    // backgroundColor: "blue", // デバッグ用（あとで消す）
    backgroundColor: col.borderColor,
  }),
  acLd4: (col) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    // height: `calc(100% - ${base} * 8)`,
    // width: `calc(100% - ${base} * 10)`,
    // backgroundColor: "blue", // デバッグ用（あとで消す）
    backgroundColor: col.borderColor,
  }),
  acLd3: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: `calc(${base} * 18)`,
    color: tone.TextColor,
    // height: `calc(100% - ${base} * 8)`,
    // width: `calc(100% - ${base} * 10)`,
    // backgroundColor: "blue", // デバッグ用（あとで消す）
    // backgroundColor: col.borderColor,
  },
  acLd2: {
    flex: 1,
    display: "grid",
    // gap: `calc(${base} * 4)`,

    backgroundColor: tone.buttonsBgColor,
    // minHeight: "100px", // ← これ
    // gridTemplateColumns: `repeat(${column}, minmax(0, 1fr))`,
  },
  basic4: (column) => ({
    flex: 1,
    display: "grid",
    // gap: `calc(${base} * 4)`,

    backgroundColor: tone.buttonsBgColor,
    // minHeight: "100px", // ← これ
    gridTemplateColumns: `repeat(${column}, minmax(0, 1fr))`,
  }),
  basic3: {
    // flex: 1,
    display: "flex",
    alignItems: "center", // 縦中央
    paddingLeft: `calc(${base} * 3)`,
    // justifyContent: "center", // 横中央（不要なら消す）
    fontWeight: "bold",
    // minWidth: 0,
    fontSize: `calc(${base} * 20)`,
    // backgroundColor: tone.OftenIndexColor,
    backgroundColor: "gray",
    // flexDirection: "row",
    width: `calc(${base} * 80)`,
    height: "100%",
  },
  acLd5: {
    display: "flex",
    alignItems: "center", // 縦中央
    // paddingLeft: `calc(${base} * 3)`,
    fontWeight: "bold",
    // fontSize: `calc(${base} * 20)`,
    // backgroundColor: tone.OftenIndexColor,
    backgroundColor: "red",
    flexDirection: "row",
    width: `calc(${base} * 90)`,
    height: "100%",
    minWidth: 0,
  },
  acLd8: (foo) => ({
    // display: "flex",
    flex: foo,
    minWidth: 0,
    position: "relative",
    // transform: "translate(-50%, -50%)",
    // top: "50%",
    // left: "50%",
    // width: `calc(100% - ${base} * 10)`,
    // height: `calc(100% - ${base} * 8)`,
    // backgroundColor: "yellow",
    //  KIRIWAKE
  }),
  acLd7: {
    // flex: 1,
    position: "relative",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    backgroundColor: "blue",
  },
  acLd12: {
    // display: "flex",
    position: "relative",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    // backgroundColor: "red",
  },
  acLd17: {
    // backgroundColor: "purple",
    fontSize: `calc(${base} * 30)`,
  },
  acLd16: {
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    position: "absolute",
    top: "0%",
    left: "0%",
    width: "100%",
    height: "100%",
    // backgroundColor: "red",
    pointerEvents: "none", // ← これでマウスイベントを無視
  },
  acLd15: {
    display: "flex",
    position: "relative",
    width: "100%",
    height: "100%",
    backgroundColor: "gray",
  },
  acLd9: (col) => ({
    display: "flex",
    position: "relative",
    height: "100%",
    backgroundColor: col.borderColor,
    // KIRIWAKE
    width: "100%",
  }),
  acLd10: {
    display: "flex",
    width: "100%",
    height: "100%",
    // backgroundColor: "purple",
    position: "relative",
  },
  acLd6: {
    display: "flex",
    flex: 1,
    backgroundColor: "blue",
    minWidth: 0,
  },
  acLd11: {
    display: "flex",
    position: "relative",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    // flexDirection: "column",
    // alignItems: "center",
    // justifyContent: "center",
    // alignItems: "stretch", // ← center をやめる
    backgroundColor: "purple",
  },
  basic2: {
    display: "flex",
    position: "relative",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    // flexDirection: "column",
    // alignItems: "center",
    // justifyContent: "center",
    // alignItems: "stretch", // ← center をやめる
    backgroundColor: "purple",
  },
  OftenHalf2: (col) => ({
    display: "flex",
    position: "relative",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: col.buttonColor,
    width: `calc(100% - ${base} * 10)`,
    height: `calc(100% - ${base} * 8)`,
    // flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  }),

  acLd1: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: tone.basicBgColor,
    // flex: row,
  },
  basic1: (row) => ({
    position: "relative",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: tone.basicBgColor,
    flex: row,
  }),
  OftenHalf1: (col) => ({
    position: "relative",
    width: "100%",
    height: "100%",
    display: "flex",
    backgroundColor: col.borderColor,
    flex: 1,
  }),
  Often3: {},
  Often2: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    // backgroundColor: "#999999",
  },
  Often1: {
    position: "absolute", // ★ 追加
    // inset: 0, // ★ 親いっぱいに被せる
    // flexDirection: "row",
    display: "flex",
    width: "100%",
    height: "100%",
    flexDirection: "column",
    // backgroundColor: "red",
  },
};

export default look;
