; alone
#Include .\alone\alone.ahk
; bar
#Include .\bar\1.ahk
#Include .\bar\2.ahk
#Include .\bar\3.ahk
#Include .\bar\4.ahk
#Include .\bar\5.ahk
#Include .\bar\mouse.ahk
; muh
#Include .\muh\1.ahk
#Include .\muh\2.ahk
#Include .\muh\3.ahk
#Include .\muh\4.ahk
#Include .\muh\5.ahk
#Include .\muh\mouse.ahk
; ctrl
#Include .\ctrl\5.ahk
; shift
#Include .\shift\1.ahk
#Include .\shift\2.ahk
#Include .\shift\5.ahk
; tab
; x2
#Include .\x2\mouse.ahk
#Include .\x2\1.ahk
#Include .\x2\2.ahk
#Include .\x2\3.ahk
#Include .\x2\4.ahk
#Include .\x2\5.ahk
; x1
#Include .\x1\mouse.ahk